version: '3.0'
services:
  rasa:
    image: mathildast/rasa-test:debugged
    ports:
      - 80:5005
    volumes:
      - ./:/app
    command:
      - run
      - --enable-api
      - --cors
      - "*"
    depends_on:
      - "actions"

  actions:
    image: mathildast/rasa-action:debugged
    volumes:
      - ./actions:/app/actions
    ports:
      - 5055:5055